### ISSUE TITLE
fix broken link

### ISSUE THREAD

**Issue by scottdangelo** [IBM/telco-customer-churn-on-icp4d#16]
[Watson Machine Learning Add On for Cloud Pak for Data](https://www.ibm.com/support/producthub/icpdata/docs/content/SSQNUZ_current/com.ibm.icpdata.doc/zen/admin/add-ons.html#add-ons__ai)
is broken.
IN prerequisites

**Comment by sandhya-nayak** [comment]
Fix has been merged - CLOSING.
