### ISSUE TITLE
pin python versions

### ISSUE THREAD

**Issue by scottdangelo** [IBM/telco-customer-churn-on-icp4d#19]
To prevent breaking changes, we should pin all versions of python packages that are installed.

**Comment by sandhya-nayak** [comment]
@scottdangelo is this still relevant? The versions are explicitly specified in [requirements.txt](https://github.com/IBM/telco-customer-churn-on-icp4d/blob/master/flaskapp/requirements.txt)

**Comment by scottdangelo** [comment]
This issue refers to the [notebook](https://github.com/IBM/telco-customer-churn-on-icp4d/blob/update-to-ICP4D-v3.0/notebooks/Telco-customer-churn-ICP4D.ipynb). I see that in the first cell of *section 1.0*

```
!pip uninstall watson-machine-learning-client -y
!pip install --user watson-machine-learning-client-v4 --upgrade | tail -n 1
!pip install --user pyspark==2.3.3 --upgrade|tail -n 1
!pip install --user scikit-learn==0.20.3 --upgrade|tail -n 1
```

We should probably pin `watson-machine-learning-client-v4`.
In the past, upgrades to the SDK or libraries have caused errors in the notebooks.
